version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-components:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run bootstrap
            - run: npm run snapshot:test
            - run: npm run build:components
            - save_cache:
                key: components-lib-{{ .Revision }}
                paths:
                  - packages/component-library/lib
                  - packages/component-library/lib/fonts

  test-goodreads:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                keys:
                  - components-lib-{{ .Revision }}
            - run: npm run bootstrap
            - run: npm run test:app
  build-goodreads:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - restore_cache:
                keys:
                  - components-lib-{{ .Revision }}
            - run: npm run bootstrap
            - run: npm run build:app
  test-integration:
    docker:
      - image: cypress/base:10
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: git submodule update --init
            - run: npm run bootstrap
            - run: npm run build:components
            - run:
                command: npm run start:app-test & npx wait-on http://127.0.0.1:3000
                background: true
            - run: npm run test:cy
workflows:
    build-and-test-components:
      jobs:
        - test-integration

