export const FETCH_META_STARTED = 'FETCH_META_STARTED'
export const FETCH_META_SUCCEEDED = 'FETCH_META_SUCCEEDED'
export const FETCH_META_FAILED = 'FETCH_META_FAILED'

export const FETCH_IMAGES_STARTED = 'FETCH_IMAGES_STARTED'
export const FETCH_IMAGES_SUCCEEDED = 'FETCH_IMAGES_SUCCEEDED'
export const FETCH_IMAGES_FAILED = 'FETCH_IMAGES_FAILED'

export const FETCH_RATING_STARTED = 'FETCH_RATING_STARTED'
export const FETCH_RATING_SUCCEEDED = 'FETCH_RATING_SUCCEEDED'
export const FETCH_RATING_FAILED = 'FETCH_RATING_FAILED'

export const fetchMeta = () => ({
  type: FETCH_META_STARTED,
})
